trigger AS_Trigger on Agent_Scheduling__c (Before Insert, Before Update, After Update) {
    if (Trigger.isBefore) {
        for (Agent_Scheduling__c ags : trigger.new){
            ags.Login_01__c = ags.Login_01F__c;
            ags.Login_02__c = ags.Login_02F__c;
            ags.Login_03__c = ags.Login_03F__c;
            ags.Login_04__c = ags.Login_04F__c;
            ags.Login_05__c = ags.Login_05F__c;
            ags.Login_06__c = ags.Login_06F__c;
            ags.Login_07__c = ags.Login_07F__c;
            ags.Login_08__c = ags.Login_08F__c;
            ags.Login_09__c = ags.Login_09F__c;
            ags.Login_10__c = ags.Login_10F__c;
            ags.Login_11__c = ags.Login_11F__c;
            ags.Login_12__c = ags.Login_12F__c;
            ags.Login_13__c = ags.Login_13F__c;
            ags.Login_14__c = ags.Login_14F__c;
            ags.Login_15__c = ags.Login_15F__c;
            ags.Login_16__c = ags.Login_16F__c;
            ags.Login_17__c = ags.Login_17F__c;
            ags.Login_18__c = ags.Login_18F__c;
            ags.Login_19__c = ags.Login_19F__c;
            ags.Login_20__c = ags.Login_20F__c;
            ags.Login_21__c = ags.Login_21F__c;
            ags.Login_22__c = ags.Login_22F__c;
            ags.Login_23__c = ags.Login_23F__c;
            ags.Login_24__c = ags.Login_24F__c;
            ags.Login_25__c = ags.Login_25F__c;
            ags.Login_26__c = ags.Login_26F__c;
            ags.Login_27__c = ags.Login_27F__c;
            ags.Login_28__c = ags.Login_28F__c;
            ags.Login_29__c = ags.Login_29F__c;
            ags.Login_30__c = ags.Login_30F__c;
            ags.Login_31__c = ags.Login_31F__c;
    
    
            // Status On Time
            ags.Status_On_Time__c = 0;
            if (ags.Status_Login_01__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_02__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_03__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_04__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_05__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_06__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_07__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_08__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_09__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_10__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_11__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_12__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_13__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_14__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_15__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_16__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_17__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_18__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_19__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_20__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_21__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_22__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_23__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_24__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_25__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_26__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_27__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_28__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_29__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_30__c == 'On Time') ags.Status_On_Time__c += 1;
            if (ags.Status_Login_31__c == 'On Time') ags.Status_On_Time__c += 1;
    
            // Status Late
            ags.Status_Late__c = 0;
            if (ags.Status_Login_01__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_02__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_03__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_04__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_05__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_06__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_07__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_08__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_09__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_10__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_11__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_12__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_13__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_14__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_15__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_16__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_17__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_18__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_19__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_20__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_21__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_22__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_23__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_24__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_25__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_26__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_27__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_28__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_29__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_30__c == 'Late') ags.Status_Late__c += 1;
            if (ags.Status_Login_31__c == 'Late') ags.Status_Late__c += 1;
    
            // Status Off
            ags.Status_Off__c = 0;
            if (ags.SS_01__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_02__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_03__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_04__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_05__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_06__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_07__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_08__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_09__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_10__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_11__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_12__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_13__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_14__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_15__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_16__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_17__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_18__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_19__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_20__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_21__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_22__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_23__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_24__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_25__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_26__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_27__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_28__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_29__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_30__c == 'Off') ags.Status_Off__c += 1;
            if (ags.SS_31__c == 'Off') ags.Status_Off__c += 1;
            
            // Status Sick Leave
            ags.Status_Sick_Leave__c = 0;
            if (ags.SS_01__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_02__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_03__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_04__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_05__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_06__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_07__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_08__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_09__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_10__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_11__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_12__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_13__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_14__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_15__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_16__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_17__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_18__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_19__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_20__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_21__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_22__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_23__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_24__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_25__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_26__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_27__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_28__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_29__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_30__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
            if (ags.SS_31__c == 'Sick Leave') ags.Status_Sick_Leave__c += 1;
    
            // Status Planned Leave
            ags.Status_Planned_Leave__c = 0;
            if (ags.SS_01__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_02__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_03__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_04__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_05__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_06__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_07__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_08__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_09__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_10__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_11__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_12__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_13__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_14__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_15__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_16__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_17__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_18__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_19__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_20__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_21__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_22__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_23__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_24__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_25__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_26__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_27__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_28__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_29__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_30__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
            if (ags.SS_31__c == 'Planned Leave') ags.Status_Planned_Leave__c += 1;
    
            // Status Meeting
            ags.Status_Meeting__c = 0;
            if (ags.SS_01__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_02__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_03__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_04__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_05__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_06__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_07__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_08__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_09__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_10__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_11__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_12__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_13__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_14__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_15__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_16__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_17__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_18__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_19__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_20__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_21__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_22__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_23__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_24__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_25__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_26__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_27__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_28__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_29__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_30__c == 'Meeting') ags.Status_Meeting__c += 1;
            if (ags.SS_31__c == 'Meeting') ags.Status_Meeting__c += 1;
    
            // Status Training
            ags.Status_Training__c = 0;
            if (ags.SS_01__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_02__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_03__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_04__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_05__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_06__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_07__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_08__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_09__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_10__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_11__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_12__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_13__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_14__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_15__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_16__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_17__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_18__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_19__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_20__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_21__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_22__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_23__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_24__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_25__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_26__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_27__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_28__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_29__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_30__c == 'Training') ags.Status_Training__c += 1;
            if (ags.SS_31__c == 'Training') ags.Status_Training__c += 1;
    
            // Status Break
            ags.Status_Break__c = 0;
            if (ags.SS_01__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_02__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_03__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_04__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_05__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_06__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_07__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_08__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_09__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_10__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_11__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_12__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_13__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_14__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_15__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_16__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_17__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_18__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_19__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_20__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_21__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_22__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_23__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_24__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_25__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_26__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_27__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_28__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_29__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_30__c == 'Break') ags.Status_Break__c += 1;
            if (ags.SS_31__c == 'Break') ags.Status_Break__c += 1;
    
            ags.Status_Available__c = ags.Status_On_Time__c + ags.Status_Late__c;
        }
    } // end before
    if (Trigger.isAfter) {
        integer i = 0;
        for (Agent_Scheduling__c ags : trigger.new){
            if(!System.isFuture() && i < 10) {
                TriggerFuture.AgentScheduling(ags.id);
            }
        }
    } // end after
}